#!/bin/bash

# Show what we execute
set -x

# MySQL authentication
MYSQLAUTH="--user=$MYSQL_USER --password=$MYSQL_PASSWORD"

# Wait for MySQL to come up.
until mysql $MYSQLAUTH -e ""; do
    echo "Failed to connect to MySQL - retrying..."
    sleep 1
done

mysql $MYSQLAUTH -e "CREATE DATABASE IF NOT EXISTS magento"

cd /var/www/magento2/htdocs
bin/magento setup:install \
	        --db-host=mysql \
		--db-name=magento \
		--db_user="$MYSQL_USER" \
		--db_pass="$MYSQL_PASSWORD" \
		--backend_frontname=admin \
		--base_url=http://$PUBLIC_HOST/ \
		--admin_lastname=Smith \
		--admin_firstname=John \
		--admin_email=john.smith@example.com \
		--admin_username=admin \
		--admin_password=magento2 \


# In production mode we pre-compute various files
php -f dev/tools/Magento/Tools/View/deploy.php
php -f dev/tools/Magento/Tools/Di/compiler.php

# Run the web server
exec /usr/sbin/apache2 -D FOREGROUND
